
public class registerABT extends javax.swing.JFrame {

    /**
     * Creates new form registerABT
     */
    public registerABT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Qsdsdsa = new javax.swing.JButton();
        qr = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(998, 541));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 86, 34));

        Qsdsdsa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Qsdsdsa.setForeground(new java.awt.Color(0, 51, 51));
        Qsdsdsa.setText("QR");
        Qsdsdsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QsdsdsaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QsdsdsaMouseExited(evt);
            }
        });
        Qsdsdsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QsdsdsaActionPerformed(evt);
            }
        });
        jPanel1.add(Qsdsdsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 60, -1));

        qr.setBackground(new java.awt.Color(0, 102, 102));
        qr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qrMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SCAN THE QR CODE");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ICON/QRRR.png"))); // NOI18N
        jLabel4.setText("]");

        javax.swing.GroupLayout qrLayout = new javax.swing.GroupLayout(qr);
        qr.setLayout(qrLayout);
        qrLayout.setHorizontalGroup(
            qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qrLayout.createSequentialGroup()
                .addGroup(qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qrLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3))
                    .addGroup(qrLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        qrLayout.setVerticalGroup(
            qrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        jPanel1.add(qr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 230, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images1/This presentation has live captioning..png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registeR registerFrame = new registeR();
        registerFrame.setVisible(true);
        registerFrame.pack();
        registerFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void QsdsdsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QsdsdsaMouseClicked
        qr.setSize(230, 240);
    }//GEN-LAST:event_QsdsdsaMouseClicked

    private void QsdsdsaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QsdsdsaMouseExited
        qr.setSize(0, 240);        // TODO add your handling code here:
    }//GEN-LAST:event_QsdsdsaMouseExited

    private void QsdsdsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QsdsdsaActionPerformed
qrcode wow = new qrcode();
     wow.setVisible(true);
     wow.pack();
     wow.setLocationRelativeTo(null);
     this.dispose();
    }//GEN-LAST:event_QsdsdsaActionPerformed

    private void qrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qrMouseEntered
        qr.setSize(230, 240);        // TODO add your handling code here:
    }//GEN-LAST:event_qrMouseEntered

    private void qrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qrMouseExited
        qr.setSize(0, 240);        // TODO add your handling code here:
    }//GEN-LAST:event_qrMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
registeR naks = new registeR();
     naks.setVisible(true);
     naks.pack();
     naks.setLocationRelativeTo(null);
     this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerABT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerABT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerABT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerABT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerABT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Qsdsdsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel qr;
    // End of variables declaration//GEN-END:variables
}
